export const foodItems = [
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
  {
    name: "Chocolate Cake",
    type: "cake",
    cost: 250,
    image: require("../assets/cake.jpeg"),
  },
  {
    name: "Vanilla Cake",
    type: "cake",
    cost: 300,
    image: require("../assets/cake1.jpeg"),
  },
  {
    name: "Fruit Dessert",
    type: "dessert",
    cost: 180,
    image: require("../assets/desserts.jpg"),
  },
  {
    name: "Ice Cream Dessert",
    type: "dessert",
    cost: 200,
    image: require("../assets/dessets1.jpg"),
  },
  {
    name: "Classic Fuchka",
    type: "fuchka",
    cost: 120,
    image: require("../assets/fuchka3_1.jpg"),
  },
  {
    name: "Fresh Juice",
    type: "juice",
    cost: 90,
    image: require("../assets/juice.jpg"),
  },
  {
    name: "Green Salad",
    type: "salad",
    cost: 110,
    image: require("../assets/salad.jpeg"),
  },
  {
    name: "Veg Noodles",
    type: "noodles",
    cost: 160,
    image: require("../assets/noddles.jpg"),
  },
  {
    name: "Cheese Pizza",
    type: "pizza",
    cost: 350,
    image: require("../assets/pizza.jpg"),
  },
  {
    name: "Chicken Pizza",
    type: "pizza",
    cost: 400,
    image: require("../assets/pizza1.jpeg"),
  },
];